from setuptools import setup, find_packages
exec(open('MateriomicTransformer/version.py').read())

setup(
  name = 'MateriomicTransformer',
  packages = find_packages(exclude=[]),
  include_package_data = True,
  version = __version__,
  license='MIT',
  description = 'Materiomic Analysis and Generation using Transformer GNN Models',
  author = 'Markus J Buehler',
  author_email = 'mbuehler@MIT.EDU',
  long_description_content_type = 'text/markdown',
  url = 'https://github.com/lamm-mit/MateriomicTransformer,/',
  keywords = [
    'artificial intelligence',
    'deep learning',
    'transformers',
    'graph generation',
    'molecular design',
    'scientific machine learning',
    'dynamical processes',
    'denoising-diffusion',
    'materials science'
  ],
  install_requires=[
    'accelerate',
    'click',
    'einops>=0.4',
    'einops-exts',
    'ema-pytorch>=0.0.3',
    'fsspec',
    'kornia',
    'numpy',
    'packaging',
    'pillow',
    'pydantic',
    'pytorch-lightning',
    'tensorflow-cpu',
    'torch',  
    'torchvision',
    'tqdm',
    'jupyterlab',
    'matplotlib',
    'scikit-learn',
    'pandas',
    'IProgress',
    'ipywidgets',
    'opencv-python',
    'seaborn',
    'rdkit',
    'py3dmol',
    'Biopython',
    'py3Dmol', 
    'torch_geometric',
      
  ],
  classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
  ],
)
